services:
  - type: web
    name: resume-job-matcher
    rootDir: app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run resume-to-job-mathcher.py --server.address=0.0.0.0 --server.port=$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0